export const POST_DETAILS = 'GET_DETAILS';
export const GET_DETAILS = 'GET_DETAILS';
export const UPDATE_DETAILS = 'UPDATE_DETAILS';
export const DELETE_DETAILS = 'DELETE_DETAILS';
export const GET_DETAILS_USER = 'GET_DETAILS_USER';